### ISSUE TITLE
please review out posts in github on project/project.md vs report/report.md

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-336#1]
please review out posts in piazza on project/project.md vs report/report.md

**Comment by mafrechette98** [comment]
Hi —
I wasn’t able to find the specific post illustrating the differences
between the two. Would you be able to link me to said post?

Thanks!
Matt Frechette

**Comment by laszewsk** [comment]
how about https://piazza.com/class/kedccsbsthm5sc?cid=186

there are some others. please start reading all piazza posts
